### ISSUE TITLE
JSON artifacts are not included into the npm module

### ISSUE THREAD

**Issue by makoto** [ensdomains/ethregistrar#11]
To enable, pleased do the following
- Please add `node_module` into `.npmignore` file like [this](https://github.com/ensdomains/dnsregistrar/blob/master/.npmignore)
- Please add `prepublishOnly` job like [this](https://github.com/ensdomains/dnsregistrar/blob/master/package.json#L42)
- Test installing the package and make sure that CONTRACT.json files are generated under `node_modules/@ensdomains/ethregistrar/build/contracts`

**Comment by decanus** [comment]
@makoto the prepublish is pretty much the same. Except of the missing npm compile which isn't necessary.
