### ISSUE TITLE
Can I derive controller contract address from the base registrar?

### ISSUE THREAD

**Issue by makoto** [ensdomains/ethregistrar#15]
It looks like baseRegistrar does not know anything about controllers it's been added (it only store the collection of controllers). When using ens-app, would it be possible to derive which controller it's been used for registering .eth address, or should we be hard code controller addresses of each network deployed?

**Comment by Arachnid** [comment]
Not at present. There's a few ways we could handle this:

 1. Add a text record to '.eth' specifying the location at which a given controller can be found.
 2. Add a mapping to the registrar from interface ID to controller, and allow controllers to specify interfaces they implement when they're added.
 3. Use a standard like [ERC820](https://eips.ethereum.org/EIPS/eip-820) to specify where to find the interface implementation.

820 is currently suffering issues relating to how they ABI encode data and new invariants introduced in 0.5 of Solidity. I'm also not a huge fan of how involved it is. Personally I'd vote we go with options 1 or 2.

**Comment by makoto** [comment]
Are there any case when more than 1 active controllers (the fact that controller is in controllers mapping I am guessing it is technically possible)? If so, one to one mapping does not really work.

**Comment by jefflau** [comment]
Down for adding it into the contract. Instead of a text record, why don't we just resolve the address of `eth` to the controller contract?

**Comment by makoto** [comment]
Can we set via ENS name like  `ethregistrarcontroller.ensdomains.eth`? Using as a text field leave no semantic of the usage

**Comment by jefflau** [comment]
I think i'd rather have it on the contract itself than using names in this case. Just so we can derive everything from just looking up the owner of the eth and then interacting with that contract

If we did go down that route, technically should have a right to `ens.eth` since we bought that domain name right? Something less wordy like `registrar.ens.eth` would be better i think. Who owns `registrar.eth`?

**Comment by Arachnid** [comment]
> Are there any case when more than 1 active controllers (the fact that controller is in controllers mapping I am guessing it is technically possible)? If so, one to one mapping does not really work.

Yes - the auction contract at least will be a controller as well.

> Down for adding it into the contract. Instead of a text record, why don't we just resolve the address of `eth` to the controller contract?

That would be a problem if we have multiple controllers, though.

> Can we set via ENS name like `ethregistrarcontroller.ensdomains.eth`? Using as a text field or using address field of `eth` leave no semantic of the usage

We could, but that won't be discoverable from the registrar either. what's wrong with text records?
