### ISSUE TITLE
Error Registering pitterpatter.eth

### ISSUE THREAD

**Issue by flanagansteve** [ensdomains/ethregistrar#32]
Hello! I'm unsure if this is the right place to report a bug, but I encountered a contract error when trying to register pitterpatter.eth:

https://etherscan.io/tx/0x23fd56096136bdab52e42a879fb962b666894f1a7ede783486a26463ad2b24cb

and a second attempt:

https://etherscan.io/tx/0x4daa7e90934aaf3f51276462e97ff81f3dbe002788944f21b883df5a662aaa6e

If this were my own contract I'd try throwing it and remix and attempting to reproduce the error but can't do that here

I'm happy to provide more details if helpful!

**Comment by Arachnid** [comment]
It looks likely that the ETH-USD value varied too much in the window between your placing the bid and it being accepted, resulting in it being rejected for insufficient funds. Can you try again now?

**Comment by flanagansteve** [comment]
Yup! Worked now.

I wonder if there's a way to report that error somehow - I know that require lets you pass a message back as require(condition, msg), but I don't know if etherscan supports presenting that yet
